"""playlist and song tables

Revision ID: b9a98d765fc4
Revises: 
Create Date: 2020-04-13 16:47:58.505157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a98d765fc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('bands', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_bands'), 'playlist', ['bands'], unique=False)
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=False)
    op.create_index(op.f('ix_playlist_year'), 'playlist', ['year'], unique=False)
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=120), nullable=True),
    sa.Column('song_name', sa.String(length=120), nullable=True),
    sa.Column('album_name', sa.String(length=120), nullable=True),
    sa.Column('release_date', sa.String(length=64), nullable=True),
    sa.Column('popularity', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.String(length=120), nullable=True),
    sa.Column('external_urls', sa.String(length=200), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_album_name'), 'song', ['album_name'], unique=False)
    op.create_index(op.f('ix_song_artist_name'), 'song', ['artist_name'], unique=False)
    op.create_index(op.f('ix_song_external_urls'), 'song', ['external_urls'], unique=False)
    op.create_index(op.f('ix_song_popularity'), 'song', ['popularity'], unique=False)
    op.create_index(op.f('ix_song_release_date'), 'song', ['release_date'], unique=False)
    op.create_index(op.f('ix_song_song_name'), 'song', ['song_name'], unique=False)
    op.create_index(op.f('ix_song_uri'), 'song', ['uri'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_uri'), table_name='song')
    op.drop_index(op.f('ix_song_song_name'), table_name='song')
    op.drop_index(op.f('ix_song_release_date'), table_name='song')
    op.drop_index(op.f('ix_song_popularity'), table_name='song')
    op.drop_index(op.f('ix_song_external_urls'), table_name='song')
    op.drop_index(op.f('ix_song_artist_name'), table_name='song')
    op.drop_index(op.f('ix_song_album_name'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_playlist_year'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_bands'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
