"""playlists table

Revision ID: cd5a0076f702
Revises: 
Create Date: 2020-04-13 12:06:03.144825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5a0076f702'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('bands', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_bands'), 'playlist', ['bands'], unique=False)
    op.create_index(op.f('ix_playlist_name'), 'playlist', ['name'], unique=False)
    op.create_index(op.f('ix_playlist_year'), 'playlist', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_year'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_name'), table_name='playlist')
    op.drop_index(op.f('ix_playlist_bands'), table_name='playlist')
    op.drop_table('playlist')
    # ### end Alembic commands ###
